medicalSoftware_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
	path('users/', include('users.urls')),
	path('users/', include('django.contrib.auth.urls')),
	path('patients/', include('patients.urls')),
	path('appointments/', include('appointments.urls')),
	path('', include('medicalSoftware.urls')),
]

users/urls.py
# users/urls.py

from django.urls import path
from .views import SignUpView

urlpatterns = [
	path('signup/', SignUpView.as_view(), name='signup'),
]

appointments/models.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse
from patients.models import Patient
from datetime import datetime

# Create your models here.

class Appointment(models.Model):
	patient = models.ForeignKey(
		Patient,
		on_delete=models.CASCADE,
	)
	purpose = models.CharField(max_length=255)
	startDate = models.DateField(default=datetime.now(), blank=True)
	startTime = models.TimeField(blank=True)
	endDate = models.DateField(default=datetime.now(), blank=True)
	endTime = models.TimeField(blank=True)
	doctor = models.ForeignKey(
		get_user_model(),
		on_delete=models.CASCADE,
	)
	
	def __str__(self):
		return str(self.patient) + ' ' + str(self.purpose) + ' on ' + str(self.startDate) + ' at ' + str(self.startTime)
	
	def get_absolute_url(self):	
		return reverse('appointment_detail', args=[str(self.id)])

patients/models.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse
from datetime import date

# Create your models here.

GENDER_CHOICES = (
	('male', 'MALE'),
	('female', 'FEMALE'),
)

MARITAL_STATUS_CHOICES = (
	('single', 'SINGLE'),
	('married', 'MARRIED'),
)

class Patient(models.Model):
	# general data
	first_name = models.CharField(max_length=255)
	last_name = models.CharField(max_length=255)
	gender = models.CharField(max_length=10, blank=True, choices=GENDER_CHOICES)
	date_of_birth = models.DateField('Date', null=True)
	marital_status = models.CharField(max_length=10, blank=True, choices=MARITAL_STATUS_CHOICES)
	nric = models.CharField(max_length=255, blank=True)
	passport = models.CharField(max_length=255, blank=True)
	nationality = models.CharField(max_length=100, blank=True)
	ethnic_race = models.CharField(max_length=100, blank=True)
	
	# contact
	mobile = models.CharField(max_length=20, blank=True)
	landline = models.CharField(max_length=20, blank=True)
	email = models.CharField(max_length=100, blank=True)
	
	# emergency contact
	emergency_contact_name = models.CharField(max_length=100, blank=True)
	emergency_phone_number = models.CharField(max_length=20, blank=True)
	emergency_relationship = models.CharField(max_length=50, blank=True)
	
	# insurance
	insurance_company = models.CharField(max_length=100, blank=True)
	insurance_policy_no = models.CharField(max_length=30, blank=True)
	
	# residential address
	residential_address_street = models.CharField(max_length=50, blank=True)
	residential_address_block = models.CharField(max_length=50, blank=True)
	residential_address_unit = models.CharField(max_length=20, blank=True)
	residential_address_postal_code = models.CharField(max_length=10, blank=True)
	residential_address_city = models.CharField(max_length=30, blank=True)
	residential_address_country = models.CharField(max_length=30, blank=True)
	
	# shipping address
	shipping_address_same = models.CharField(max_length=1, blank=True)
	shipping_address_street = models.CharField(max_length=50, blank=True)
	shipping_address_block = models.CharField(max_length=50, blank=True)
	shipping_address_unit = models.CharField(max_length=20, blank=True)
	shipping_address_postal_code = models.CharField(max_length=10, blank=True)
	shipping_address_city = models.CharField(max_length=30, blank=True)
	shipping_address_country = models.CharField(max_length=30, blank=True)
	
	# billing address
	billing_address_same = models.CharField(max_length=1, blank=True)
	billing_address_street = models.CharField(max_length=50, blank=True)
	billing_address_block = models.CharField(max_length=50, blank=True)
	billing_address_unit = models.CharField(max_length=20, blank=True)
	billing_address_postal_code = models.CharField(max_length=10, blank=True)
	billing_address_city = models.CharField(max_length=30, blank=True)
	billing_address_country = models.CharField(max_length=30, blank=True)
	
	doctor = models.ForeignKey(
		get_user_model(),
		on_delete=models.CASCADE,
	)
		
	def __str__(self):
		return self.first_name
		
	def get_absolute_url(self):
		return reverse('patient_detail', args=[str(self.id)])
		

appointments/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from django.views.generic.edit import UpdateView, DeleteView, CreateView
from django.urls import reverse_lazy

from .forms import AppointmentForm
from .models import Appointment

from datetime import datetime
from pytz import timezone, utc
from django.conf import settings

from django.contrib.auth import get_user_model

from django.http import JsonResponse
import pdb;

# Create your views here.

class AppointmentListView(ListView):
	model = Appointment
	template_name = 'appointment_list.html'
	# This is our new breakpoint
	#pdb.set_trace()
	
class AppointmentDetailView(DetailView):
	model = Appointment
	template_name = 'appointment_detail.html'

class AppointmentUpdateView(UpdateView):
	model = Appointment
	form_class = AppointmentForm
	#fields = ('patient', 'purpose', 'startDate', 'startTime', 'endDate', 'endTime', 'doctor')
	template_name = 'appointment_edit.html'
	
class AppointmentDeleteView(DeleteView):
	model = Appointment
	template_name = 'appointment_delete.html'
	success_url = reverse_lazy('appointment_list')

class AppointmentCreateView(CreateView):
	model = Appointment
	#form_class = AppointmentForm
	fields = ('patient', 'purpose', 'startDate', 'startTime', 'endDate', 'endTime', 'doctor')
	template_name = 'appointment_new.html'
	

def appointment_calendar(request):		
	schedules = []	
	scheduleRow = {}	
	doctorIDs = []
	doctors = []
	doctorRow = {}
		
	queryset = Appointment.objects.values()
	
	
	for row in queryset:
		#scheduleRow = {'id': row['id'], 'calendarId': row['patient_id'], 'title': row['purpose'], 'category': 'time', 'dueDateClass': '', 'start': row['startDate'].strftime('%Y-%m-%d') + 'T' + row['startTime'].strftime('%I:%M:%S') + '+08:00', 'end': row['endDate'].strftime('%Y-%m-%d') + 'T' + row['endTime'].strftime('%I:%M') + '+08:00', 'bgColor': '#37EAE1', 'attendees': [getattr(get_user_model().objects.get(id=row['doctor_id']), 'first_name')]}
		scheduleRow = {'id': row['id'], 'calendarId': row['patient_id'], 'title': row['purpose'], 'body': row['purpose'], 'category': 'time', 'dueDateClass': '', 'start': utcisoformat(datetime(row['startDate'].year, row['startDate'].month, row['startDate'].day, row['startTime'].hour, row['startTime'].minute, row['startTime'].second)), 'end': utcisoformat(datetime(row['endDate'].year, row['endDate'].month, row['endDate'].day, row['endTime'].hour, row['endTime'].minute, row['endTime'].second)), 'bgColor': '#37EAE1', 'attendees': [getattr(get_user_model().objects.get(id=row['doctor_id']), 'first_name')]}
		schedules.append(scheduleRow)
		
		if row['doctor_id'] not in doctorIDs:
			doctorIDs.append(row['doctor_id']);
		

	for doctorID in doctorIDs:
		doctorRow = {
			'doctor_id': doctorID, 
			'first_name': getattr(get_user_model().objects.get(id=doctorID), 'first_name'), 
			'last_name': getattr(get_user_model().objects.get(id=doctorID), 'last_name')
		}
		doctors.append(doctorRow)
		
	#pdb.set_trace()
	
	
	return JsonResponse(data={
		'schedules': schedules,
		'doctors': doctors
	})
	
def select_doctor(request):
	schedules = []	
	scheduleRow = {}	
	doctorIDs = []
	doctors = []
	doctorRow = {}
	
	# get filter
	if (request.method=='GET'):
		filter_doctor_id = request.GET['doctor_id']
	
	queryset = Appointment.objects.filter(doctor_id=filter_doctor_id).values()
	
	#pdb.set_trace()
	
	for row in queryset:
		scheduleRow = {'id': row['id'], 'calendarId': row['patient_id'], 'title': row['purpose'], 'body': row['purpose'], 'category': 'time', 'dueDateClass': '', 'start': utcisoformat(datetime(row['startDate'].year, row['startDate'].month, row['startDate'].day, row['startTime'].hour, row['startTime'].minute, row['startTime'].second)), 'end': utcisoformat(datetime(row['endDate'].year, row['endDate'].month, row['endDate'].day, row['endTime'].hour, row['endTime'].minute, row['endTime'].second)), 'bgColor': '#37EAE1', 'attendees': [getattr(get_user_model().objects.get(id=row['doctor_id']), 'first_name')]}
		schedules.append(scheduleRow)
		
		if row['doctor_id'] not in doctorIDs:
			doctorIDs.append(row['doctor_id']);	
		
	for doctorID in doctorIDs:
		doctorRow = {
			'doctor_id': doctorID, 
			'first_name': getattr(get_user_model().objects.get(id=doctorID), 'first_name'), 
			'last_name': getattr(get_user_model().objects.get(id=doctorID), 'last_name')
		}		
		doctors.append(doctorRow)
	
	return JsonResponse(data={
		'schedules': schedules
	})

def utcisoformat(dt):
    """
    Return a datetime object in ISO 8601 format in UTC, without microseconds
    or time zone offset other than 'Z', e.g. '2011-06-28T00:00:00Z'. Useful
    for making Django DateTimeField values compatible with the
    jquery.localtime plugin.
    """
    # Convert datetime to UTC, remove microseconds, remove timezone, convert to string
    return timezone(settings.TIME_ZONE).localize(dt.replace(microsecond=0)).astimezone(utc).replace(tzinfo=None).isoformat() + 'Z'
	
# def update_appointment(request):
	# if 'doctor_id' in request.POST:
		# Appointment.objects.filter(id=request.POST['doctor_id']).update(startDate=

templates/appointment_edit.html
<!-- templates/appointment_edit.html -->
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block content %}
	<h1>Edit Appointment Information</h1>
	<form action="" method="post">{% csrf_token %}
		<div class="label-settings">			
			<label for="id_patient">Patient</label>{{ form.patient }}
			<label for="id_purpose">Purpose</label>{{ form.purpose }}
			<label for="id_startDate">Start Date</label>{% render_field form.startDate type='date' %}			
			<label for="id_startTime">Start Time</label>{% render_field form.startTime type='time' %}
			<label for="id_endDate">End Date</label>{% render_field form.endDate type='date' %}
			<label for="id_endTime">End Time</label>{% render_field form.endTime type='time' %}
			<label for="id_doctor">Doctor</label>{{ form.doctor }}
		</div>		
		<button class="btn btn-success ml-2" type="submit">Save</button>
	</form>
{% endblock content %}

templates/appointment_new.html
<!-- templates/appointment_edit.html -->
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block content %}
	<h1>Edit Appointment Information</h1>
	<form action="" method="post">{% csrf_token %}
		<div class="label-settings">			
			<label for="id_patient">Patient</label>{{ form.patient }}
			<label for="id_purpose">Purpose</label>{{ form.purpose }}
			<label for="id_startDate">Start Date</label>{% render_field form.startDate type='date' %}
			<label for="id_startTime">Start Time</label>{% render_field form.startTime type='time' %}
			<label for="id_endDate">End Date</label>{% render_field form.endDate type='date' %}
			<label for="id_endTime">End Time</label>{% render_field form.endTime type='time' %}
			<label for="id_doctor">Doctor</label>{{ form.doctor }}
		</div>		
		<button class="btn btn-success ml-2" type="submit">Save</button>
	</form>
{% endblock content %}

templates/home.html
<!-- templates/home.html -->

{% extends 'base.html' %}

{% block content %}
			
		<!-- <style>
			a:link, a:visited {
			  background-color: #f44336;
			  color: white;
			  padding: 14px 25px;
			  text-align: center;
			  text-decoration: none;
			  display: inline-block;				
			}

			a:hover, a:active {
			  background-color: red;
			}			
		</style> -->
	<p>Home Page</p>
	<section class="main clearfix">
		<a class="link-box" href="{% url 'patient_list' %}">Register Patient</a>				
		<a class="link-box" href="{% url 'appointment_list' %}">Book Appointment</a>
		</div>
	</section>
	
{% endblock content %}

templates/patient_detail.html
<!-- templates/patient_detail.html -->
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block content %}
<form action="" method="get">{% csrf_token %}
	<h1>Patient Information</h1>
	<h3>General Data</h3>
	<div class="label-settings">			
		<label for="id_first_name">First Name</label>
		{% if not object.first_name %}			
			</br>
		{% else %}
			{{ object.first_name }}
		{% endif %}
		<label for="id_last_name">Last Name</label>
		{% if not object.last_name %}			
			</br>
		{% else %}
			{{ object.last_name }}
		{% endif %}
		<label for="id_gender">Gender</label>
		{% if not object.gender %}			
			</br>
		{% else %}
			{{ object.gender }}
		{% endif %}
		<label for="id_date_of_birth">Date of Birth</label>
		{% if not object.date_of_birth %}			
			</br>
		{% else %}
			{{ object.date_of_birth }}
		{% endif %}
		<label for="id_nric">NRIC</label>
		{% if not object.nric %}			
			</br>
		{% else %}
			{{ object.nric }}
		{% endif %}
		<label for="id_passport">Passport</label>
		{% if not object.passport %}			
			</br>
		{% else %}
			{{ object.passport }}
		{% endif %}
		<label for="id_nationality">Nationality</label>
		{% if not object.nationality %}			
			</br>
		{% else %}
			{{ object.nationality }}
		{% endif %}
		<label for="id_ethnic_race">Ethnic Race</label>
		{% if not object.ethnic_race %}			
			</br>
		{% else %}
			{{ object.ethnic_race }}
		{% endif %}
	</div>
	
	<h3>Contact</h3>
	<div class="label-settings">			
		<label for="id_mobile">Mobile</label>
		{% if not object.mobile %}			
			</br>
		{% else %}
			{{ object.mobile }}
		{% endif %}
		<label for="id_landline">Landline</label>
		{% if not object.landline %}			
			</br>
		{% else %}
			{{ object.landline }}
		{% endif %}
		<label for="id_email">Email</label>
		{% if not object.email %}			
			</br>
		{% else %}
			{{ object.email }}
		{% endif %}
		<label for="id_doctor">Doctor</label>	
		{% if not object.doctor %}			
			</br>
		{% else %}
			{{ object.doctor }}
		{% endif %}		
	</div>
	
	<h3>Emergency Contact</h3>
	<div class="label-settings">			
		<label for="id_emergency_contact_name">Name</label>
		{% if not object.emergency_contact_name %}			
			</br>
		{% else %}
			{{ object.emergency_contact_name }}
		{% endif %}
		<label for="id_emergency_phone_number">Phone</label>
		{% if not object.emergency_phone_number %}			
			</br>
		{% else %}
			{{ object.emergency_phone_number }}
		{% endif %}
		<label for="id_emergency_relationship">Relationship</label>
		{% if not object.emergency_relationship %}			
			</br>
		{% else %}
			{{ object.emergency_relationship }}
		{% endif %}
	</div>
	
	<h3>Insurance</h3>
	<div class="label-settings">			
		<label for="id_insurance_company">Company</label>
		{% if not object.insurance_company %}			
			</br>
		{% else %}
			{{ object.insurance_company }}
		{% endif %}
		<label for="id_insurance_policy_no">Policy No.</label>
		{% if not object.insurance_policy_no %}			
			</br>
		{% else %}
			{{ object.insurance_policy_no }}
		{% endif %}
	</div>
	
	<h3>Residential Address</h3>
	<div class="label-settings">			
		<label for="id_residential_address_street">Street</label>
		{% if not object.residential_address_street %}			
			</br>
		{% else %}
			{{ object.residential_address_street }}
		{% endif %}
		<label for="id_residential_address_block">Block</label>
		{% if not object.residential_address_block %}			
			</br>
		{% else %}
			{{ object.residential_address_block }}
		{% endif %}
		<label for="id_residential_address_unit">Unit</label>
		{% if not object.residential_address_unit %}			
			</br>
		{% else %}
			{{ object.residential_address_unit }}
		{% endif %}
		<label for="id_residential_address_postal_code">Postal Code</label>
		{% if not object.residential_address_postal_code %}			
			</br>
		{% else %}
			{{ object.residential_address_postal_code }}
		{% endif %}
		<label for="id_residential_address_city">City</label>
		{% if not object.residential_address_city %}			
			</br>
		{% else %}
			{{ object.residential_address_city }}
		{% endif %}
		<label for="id_residential_address_country">Country</label>
		{% if not object.residential_address_country %}			
			</br>
		{% else %}
			{{ object.residential_address_country }}
		{% endif %}
	</div>
	
	<h3>Shipping Address</h3>
	{% if not object.shipping_address_same %}
		<input type="checkbox" disabled=true />
	{% else %}	
		<input type="checkbox" disabled=true checked />
	{% endif %}
	<label for="id_shipping_address_same">Same as residential address</label>
	<div class="label-settings">						
		<label for="id_shipping_address_street">Street</label>
		{% if not object.shipping_address_street %}			
			</br>
		{% else %}
			{{ object.shipping_address_street }}
		{% endif %}
		<label for="id_shipping_address_block">Block</label>
		{% if not object.shipping_address_block %}			
			</br>
		{% else %}
			{{ object.shipping_address_block }}
		{% endif %}
		<label for="id_shipping_address_unit">Unit</label>
		{% if not object.shipping_address_unit %}			
			</br>
		{% else %}
			{{ object.shipping_address_unit }}
		{% endif %}
		<label for="id_shipping_address_postal_code">Postal Code</label>
		{% if not object.shipping_address_postal_code %}			
			</br>
		{% else %}
			{{ object.shipping_address_postal_code }}
		{% endif %}
		<label for="id_shipping_address_city">City</label>
		{% if not object.shipping_address_city %}			
			</br>
		{% else %}
			{{ object.shipping_address_city }}
		{% endif %}
		<label for="id_shipping_address_country">Country</label>
		{% if not object.shipping_address_country %}			
			</br>
		{% else %}
			{{ object.shipping_address_country }}
		{% endif %}
	</div>
	
	<h3>Billing Address</h3>
	{% if not object.billing_address_same %}
		<input type="checkbox" disabled=true />
	{% else %}	
		<input type="checkbox" disabled=true checked />
	{% endif %}	
	<label for="id_billing_address_same">Same as shipping address</label>
	<div class="label-settings">								
		<label for="id_billing_address_street">Street</label>
		{% if not object.billing_address_street %}			
			</br>
		{% else %}
			{{ object.billing_address_street }}
		{% endif %}
		<label for="id_billing_address_block">Block</label>
		{% if not object.billing_address_block %}			
			</br>
		{% else %}
			{{ object.billing_address_block }}
		{% endif %}
		<label for="id_billing_address_unit">Unit</label>
		{% if not object.billing_address_unit %}			
			</br>
		{% else %}
			{{ object.billing_address_unit }}
		{% endif %}
		<label for="id_billing_address_postal_code">Postal Code</label>
		{% if not object.billing_address_postal_code %}			
			</br>
		{% else %}
			{{ object.billing_address_postal_code }}
		{% endif %}
		<label for="id_billing_address_city">City</label>
		{% if not object.billing_address_city %}			
			</br>
		{% else %}
			{{ object.billing_address_city }}
		{% endif %}
		<label for="id_billing_address_country">Country</label>
		{% if not object.billing_address_country %}			
			</br>
		{% else %}
			{{ object.billing_address_country }}
		{% endif %}
	</div>
</form>
<p><a href="{% url 'patient_edit' patient.pk %}">Edit</a> | <a href="{% url 'patient_delete' patient.pk %}">Delete</a></p>
<p>Back to <a href="{% url 'patient_list' %}">All patients</a>.</p>
{% endblock content %}

templates/patient_new.html
<!-- templates/patient_new.html -->
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block content %}
	<script>
		function updateShippingAddress() {
			if (document.getElementById("id_shipping_address_same").checked == true) {
				document.getElementById("id_shipping_address_street").value = document.getElementById("id_residential_address_street").value;
				document.getElementById("id_shipping_address_block").value = document.getElementById("id_residential_address_block").value;
				document.getElementById("id_shipping_address_unit").value = document.getElementById("id_residential_address_unit").value;
				document.getElementById("id_shipping_address_postal_code").value = document.getElementById("id_residential_address_postal_code").value;
				document.getElementById("id_shipping_address_city").value = document.getElementById("id_residential_address_city").value;
				document.getElementById("id_shipping_address_country").value = document.getElementById("id_residential_address_country").value;
				
				document.getElementById("id_shipping_address_street").disabled = true;
				document.getElementById("id_shipping_address_block").disabled = true;
				document.getElementById("id_shipping_address_unit").disabled = true;
				document.getElementById("id_shipping_address_postal_code").disabled = true;
				document.getElementById("id_shipping_address_city").disabled = true;
				document.getElementById("id_shipping_address_country").disabled = true;
			}
			else {				
				document.getElementById("id_shipping_address_street").disabled = false;
				document.getElementById("id_shipping_address_block").disabled = false;
				document.getElementById("id_shipping_address_unit").disabled = false;
				document.getElementById("id_shipping_address_postal_code").disabled = false;
				document.getElementById("id_shipping_address_city").disabled = false;
				document.getElementById("id_shipping_address_country").disabled = false;
			}
		}
		
		function updateBillingAddress() {
			if (document.getElementById("id_billing_address_same").checked == true) {
				document.getElementById("id_billing_address_street").value = document.getElementById("id_shipping_address_street").value;
				document.getElementById("id_billing_address_block").value = document.getElementById("id_shipping_address_block").value;
				document.getElementById("id_billing_address_unit").value = document.getElementById("id_shipping_address_unit").value;
				document.getElementById("id_billing_address_postal_code").value = document.getElementById("id_shipping_address_postal_code").value;
				document.getElementById("id_billing_address_city").value = document.getElementById("id_shipping_address_city").value;
				document.getElementById("id_billing_address_country").value = document.getElementById("id_shipping_address_country").value;
				
				document.getElementById("id_billing_address_street").disabled = true;
				document.getElementById("id_billing_address_block").disabled = true;
				document.getElementById("id_billing_address_unit").disabled = true;
				document.getElementById("id_billing_address_postal_code").disabled = true;
				document.getElementById("id_billing_address_city").disabled = true;
				document.getElementById("id_billing_address_country").disabled = true;
			}
			else {				
				document.getElementById("id_billing_address_street").disabled = false;
				document.getElementById("id_billing_address_block").disabled = false;
				document.getElementById("id_billing_address_unit").disabled = false;
				document.getElementById("id_billing_address_postal_code").disabled = false;
				document.getElementById("id_billing_address_city").disabled = false;
				document.getElementById("id_billing_address_country").disabled = false;
			}
		}
	</script>
	<h1>New patient</h1>
	<form action="" method="post">{% csrf_token %}
		<h3>General Data</h3>
		<div class="label-settings">			
			<label for="id_first_name">First Name</label>{{ form.first_name }}
			<label for="id_last_name">Last Name</label>{{ form.last_name }}
			<label for="id_gender">Gender</label>{{ form.gender }}
			<label for="id_date_of_birth">Date of Birth</label>{% render_field form.date_of_birth type='date' %}
			<label for="id_nric">NRIC</label>{{ form.nric }}
			<label for="id_passport">Passport</label>{{ form.passport }}
			<label for="id_nationality">Nationality</label>{{ form.nationality }}
			<label for="id_ethnic_race">Ethnic Race</label>{{ form.ethnic_race }}
		</div>
		
		<h3>Contact</h3>
		<div class="label-settings">			
			<label for="id_mobile">Mobile</label>{{ form.mobile }}
			<label for="id_landline">Landline</label>{{ form.landline }}
			<label for="id_email">Email</label>{{ form.email }}
			<label for="id_doctor">Doctor</label>{{ form.doctor }}			
		</div>
		
		<h3>Emergency Contact</h3>
		<div class="label-settings">			
			<label for="id_emergency_contact_name">Name</label>{{ form.emergency_contact_name }}
			<label for="id_emergency_phone_number">Phone</label>{{ form.emergency_phone_number }}
			<label for="id_emergency_relationship">Relationship</label>{{ form.emergency_relationship }}
		</div>
		
		<h3>Insurance</h3>
		<div class="label-settings">			
			<label for="id_insurance_company">Company</label>{{ form.insurance_company }}
			<label for="id_insurance_policy_no">Policy No.</label>{{ form.insurance_policy_no }}
		</div>
		
		<h3>Residential Address</h3>
		<div class="label-settings">			
			<label for="id_residential_address_street">Street</label>{{ form.residential_address_street }}
			<label for="id_residential_address_block">Block</label>{{ form.residential_address_block }}
			<label for="id_residential_address_unit">Unit</label>{{ form.residential_address_unit }}
			<label for="id_residential_address_postal_code">Postal Code</label>{{ form.residential_address_postal_code }}
			<label for="id_residential_address_city">City</label>{{ form.residential_address_city }}
			<label for="id_residential_address_country">Country</label>{{ form.residential_address_country }}	
		</div>
		
		<h3>Shipping Address</h3>
		{% render_field form.shipping_address_same type='checkbox' vertical-align="middle" position="relative" onclick="updateShippingAddress()" %}	
		<label for="id_shipping_address_same">Same as residential address</label>
		<div class="label-settings">						
			<label for="id_shipping_address_street">Street</label>{{ form.shipping_address_street }}
			<label for="id_shipping_address_block">Block</label>{{ form.shipping_address_block }}
			<label for="id_shipping_address_unit">Unit</label>{{ form.shipping_address_unit }}
			<label for="id_shipping_address_postal_code">Postal Code</label>{{ form.shipping_address_postal_code }}
			<label for="id_shipping_address_city">City</label>{{ form.shipping_address_city }}
			<label for="id_shipping_address_country">Country</label>{{ form.shipping_address_country }}
		</div>
		
		<h3>Billing Address</h3>
		{% render_field form.billing_address_same type='checkbox' vertical-align="middle" position="relative" onclick="updateBillingAddress()" %}	
		<label for="id_billing_address_same">Same as shipping address</label>
		<div class="label-settings">								
			<label for="id_billing_address_street">Street</label>{{ form.billing_address_street }}
			<label for="id_billing_address_block">Block</label>{{ form.billing_address_block }}
			<label for="id_billing_address_unit">Unit</label>{{ form.billing_address_unit }}
			<label for="id_billing_address_postal_code">Postal Code</label>{{ form.billing_address_postal_code }}
			<label for="id_billing_address_city">City</label>{{ form.billing_address_city }}
			<label for="id_billing_address_country">Country</label>{{ form.billing_address_country }}	
		</div>
		<button class="btn btn-success ml-2" type="submit">Save</button>
	</form>
{% endblock content %}

templates/register_patient.html
<!-- templates/home.html -->

{% extends 'base.html' %}

{% block content %}
	
	<p>Register Patient Page</p>
	
{% endblock content %}